#Keycloak/OAuth properties
security:
  oauth2:
    resource:
      jwt:
        key-value: ${KEYCLOAK_PUBLIC_KEY}

#DB Properties
spring:
  jmx:
    enabled: false
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  #Keycloak/OAuth properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URL}
          jwk-set-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/certs

#Logging properties
logging:
  file:
    name: /logs/app.log
  logback:
    rollingpolicy:
      max-history: 1
      max-file-size: 20MB
      clean-history-on-start: true
  pattern:
    file: '{"time_stamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%3p" ,"thread":"%t" ,"class":"%logger{36}","msg":"%replace(%msg){"[\n\r\"]",""}", "exception":"%replace(%rEx{10}){"[\n\r\"]",""}","http_event":%X{httpEvent:-""},"message_event":%X{messageEvent:-""}}%nopex%n'
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] [%t] [%logger{36}] [%replace(%msg){'[\n\r\"]',''} %X{httpEvent} %X{messageEvent}] %replace(%rEx{10}){'[\n\r\"]',''}%nopex%n"
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              gradbusiness: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Resilience
resilience4j.retry:
  instances:
    searchbypen:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    advancedsearch:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 30s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    searchbyid:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    generalpostcall:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 3s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    generalgetcall:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 3s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException

#Endpoint properties
endpoint:
  pen-student-api:
    by-studentid:
      url: ${PEN_API}api/v1/student/%s
    search:
      url: ${PEN_API}api/v1/student/paginated
    by-pen:
      url: ${PEN_API}api/v1/student?pen=%s
    student:
      url: ${PEN_API}api/v1/student
  grad-graduation-api:
    report-data-by-pen:
      url: ${GRAD_GRADUATION_API}api/v1/graduate/report/data/%s
    report-data-by-graduation:
      url: ${GRAD_GRADUATION_API}api/v1/graduate/report/data
  grad-report-api:
    report-data-by-xml:
      url: ${REPORT_API}api/v1/reports/xmltranscriptreport
  grad-student-api:
    demographic:
      url: ${GRAD_STUDENT_API}api/v1/student/demog/pen/%s
    amalgamated-students:
      url: ${GRAD_STUDENT_API}api/v1/student/amalgamated/schoolreport/%s/type/%s
  grad-graduation-report-api:
    school-report-by-mincode:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/schoolreport?mincode=%s&reportType=%s
    student-credential-by-type:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/business/studentcredential/%s/%s

#Splunk LogHelper
splunk:
  log-helper:
    enabled: ${ENABLE_SPLUNK_LOG_HELPER}