#Keycloak/OAuth properties
security:
  oauth2:
    resource:
      jwt:
        key-value: ${KEYCLOAK_PUBLIC_KEY}

#DB Properties
spring:
  jmx:
    enabled: false
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false

#Logging properties
logging:
  file:
    max-history: 1
    clean-history-on-start: true
    max-size: 20MB
    name: /logs/app.log
  #pattern:
  #  file: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  #  console: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              gradbusiness: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Resilience
resilience4j.retry:
  instances:
    searchbypen:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    advancedsearch:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 30s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    searchbyid:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    generalpostcall:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 3s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    generalgetcall:
      maxRetryAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 3s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException

#Endpoint properties
endpoint:
  pen-student-api:
    by-studentid:
      url: ${PEN_API}api/v1/student/%s
    search:
      url: ${PEN_API}api/v1/student/paginated
    by-pen:
      url: ${PEN_API}api/v1/student?pen=%s
    student:
      url: ${PEN_API}api/v1/student
    demographic:
       url: ${GRAD_STUDENT_API}api/v1/student/demog/pen/%s
  grad-graduation-api:
    report-data-by-pen:
      url: ${GRAD_GRADUATION_API}api/v1/graduate/report/data/%s
    report-data-by-graduation:
      url: ${GRAD_GRADUATION_API}api/v1/graduate/report/data
  grad-report-api:
    report-data-by-xml:
      url: ${GRAD_REPORT_API}api/v1/reports/xmltranscriptreport
  grad-student-api:
    demographic:
      url: ${GRAD_STUDENT_API}api/v1/student/demog/pen/%s

