services:
- name: educ-grad-business
  host: educ-grad-business-api.77c02f-tools.svc.cluster.local
  tags: [ ns.educ-grad-dev ]
  port: 8080
  protocol: http
  retries: 0
  routes:
  - name: educ-grad-business-route
    tags: [ ns.educ-grad-dev ]
    hosts:
    - educ-grad-business.dev.api.gov.bc.ca
    paths:
    - /
    methods:
    - GET
    - PUT
    - POST
    - DELETE
    - HEAD
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0