# This workflow builds to dev any direct commits to the release branch or pull requests (note there is no 'merge' trigger for github actions)

name: On Merge to Release Branch

on:
  workflow_dispatch:
  push:
    branches: 
      - release
      
jobs:

  build-and-deploy:
    name: Build, package and deploy to Dev
    runs-on: ubuntu-latest
    steps:
    - name: Git pull
      uses: actions/checkout@v3
    - name: Set up JDK 11
      run: echo "Setting up jdk 11"
    - name: Build with Maven
      run: echo "Building with maven"
    - name: Creating docker image
      run: echo "Creating docker image"
    - name: Push to registry
      run: echo "Pushing image to registry"
    - name: Install OC
      run: echo "Installing OC"
    - name: Deploy to environment
      run: echo "Deploying to DEV on OpenShift"
      
  run-smoke-test:
    name: Run Smoke Tests
    needs: [build-and-deploy]
    uses: bcgov/EDUC-GRAD-TEST-AUTOMATION/.github/workflows/test.smoke-test.yml@main
    with:
      BASE_URL: https://dev.grad.gov.bc.ca/?login=noidir
    secrets:
      TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
      TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
      TEST_PEN: ${{ secrets.TEST_PEN }} 
