# This workflow builds to dev any direct commits to the release branch or pull requests (note there is no 'merge' trigger for github actions)

name: On Merge to Release Branch

on:
  workflow_dispatch:
  #push:
    #branches: 
      #- grad-release

env:
  APP_NAME: grad-business-api
      
jobs:
  build-and-deploy:
    name: Build, package and deploy to Dev
    environment: dev
    runs-on: ubuntu-22.04
    steps:
    - name: Git pull
      uses: actions/checkout@v4
    - name: Login to Artifactory
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_ARTIFACTORY_REPO }}
        username: ${{ secrets.DOCKER_ARTIFACTORY_USERNAME }}
        password: ${{ secrets.DOCKER_ARTIFACTORY_ACCESS_TOKEN }}

    # https://github.com/redhat-actions/buildah-build#readme
    - name: Build api from Dockerfile
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}

        # If you don't have a Dockerfile/Containerfile, refer to https://github.com/redhat-actions/buildah-build#scratch-build-inputs
        # Or, perform a source-to-image build using https://github.com/redhat-actions/s2i-build
        # Otherwise, point this to your Dockerfile/Containerfile relative to the repository root.
        dockerfiles: |
          ./backend/Dockerfile
        context: ./backend

      # https://github.com/redhat-actions/push-to-registry#readme
    - name: Push backend to registry
      id: push-image-backend
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.IMAGE_REGISTRY_USER }}
        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
    - name: Install OC
      run: echo "Installing OC"
    - name: Deploy to environment
      run: echo "Deploying to DEV on OpenShift"
      
  run-smoke-test:
    name: Run Smoke Tests
    needs: [build-and-deploy]
    uses: bcgov/EDUC-GRAD-TEST-AUTOMATION/.github/workflows/test.smoke-test.yml@main
    with:
      BASE_URL: https://dev.grad.gov.bc.ca/?login=noidir
    secrets:
      TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
      TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
      TEST_PEN: ${{ secrets.TEST_PEN }} 
